on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
    - name: Install dependencies
    uses: actions/setup-node@v2
      with:
      node-version: '14'  
        
    - name:  Install npm dependencies
      run: npm install
      
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp-quai-antique-restaurant42.alwaysdata.net
        username: quai-antique-restaurant42
        password: ${secrets.ftp_password}
        server-dir: /www/
        protocol: ftps
        exclude: |
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap/js/**
          **/node_modules/bootstrap-icons/icons/** 
